version: '3.9'

services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      - 'POSTGRES_DB=SkillHub-DB'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5444:5432'