spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/SkillHub-DB
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create

jwt:
  secret:
    key: "356adb44883df62d6ef6ba54faf42945c9ca704f7069f975898d1f7210ad05f6"
  expiration: 48h