# Что нужно сделать, чтобы отправлялись сообщения по электронной почте:
# в username указать рабочую google почту
# Необходимо включить в настройках данного google аккаунта двухфакторную аутентификацию (важно)
# там же в настройках сгенерировать "Пароль приложений"
# Далее вписать сгенерированный код в password
# email:
#   username: ... - отображаемая почта, которая будет указываться в качестве отправителя

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: geragets@gmail.com
    password: heta usdn jdhe xwvm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5444/SkillHub-DB
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create

email:
  username: geragets@gmail.com

jwt:
  secret:
    key: "356adb44883df62d6ef6ba54faf42945c9ca704f7069f975898d1f7210ad05f6"
  expiration: 48h